name: capstone
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pre-commit=2.16
  - matplotlib=3.5
  - numpy=1.21
  - pandas=1.3
  - pip=21.3
  - pytest=6.2
  - requests=2.26
  - seaborn=0.11
  - scipy=1.7
  - scikit-learn=1.0
  - statsmodels=0.13
  - urllib3=1.26
  - dagster=0.15.3
  - dagit=0.15.3
  - intake
  - panel
  - holoviews
  - scikit-learn
  - bokeh
  - hvplot
  - param
  - nltk
  - sumy
  - factor_analyzer
